[package]
name = "axum-web"
version = "0.1.0"
edition = "2021"
authors = ["Sheroz Khaydarov"]
description = "Web samples using axum"
readme = "README.md"
repository = "https://github.com/sheroz/axum-web"
license = "MIT"

[dependencies]
dotenv = "0.15"
bytes = "1"
axum = { version = "0.7" }
hyper = { version = "1.0", features = ["full"] }
http-body-util = { version = "0.1" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
redis = { version = "0.24", features = ["tokio-comp"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
hyper-util = { version = "0.1", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.11" }