version: "3.1"
services:
  redis:
    image: redis:alpine
    volumes:
      - redis:/data      
    ports:
      - '6379:6379'

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres:postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"

volumes:
  redis:
  postgres:
  pgadmin:
